CPE = "cpe:/a:apache:hadoop";
if(description){
	script_oid( "1.3.6.1.4.1.25623.1.0.811401" );
	script_version( "2021-09-13T12:01:42+0000" );
	script_cve_id( "CVE-2015-1776" );
	script_bugtraq_id( 83259 );
	script_tag( name: "cvss_base", value: "2.1" );
	script_tag( name: "cvss_base_vector", value: "AV:L/AC:L/Au:N/C:P/I:N/A:N" );
	script_tag( name: "last_modification", value: "2021-09-13 12:01:42 +0000 (Mon, 13 Sep 2021)" );
	script_tag( name: "severity_vector", value: "CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N" );
	script_tag( name: "severity_origin", value: "NVD" );
	script_tag( name: "severity_date", value: "2016-11-28 19:18:00 +0000 (Mon, 28 Nov 2016)" );
	script_tag( name: "creation_date", value: "2017-06-27 20:31:53 +0530 (Tue, 27 Jun 2017)" );
	script_name( "Apache Hadoop 'MapReduce' Information Disclosure Vulnerability" );
	script_tag( name: "summary", value: "The host is installed with Apache Hadoop
  and is prone to an information disclosure vulnerability." );
	script_tag( name: "vuldetect", value: "Checks if a vulnerable version is present on the target host." );
	script_tag( name: "insight", value: "The flaw exists due to apache hadoop encrypts
  intermediate data generated by a MapReduce job and stores it along with the
  encryption key in a credentials file on disk when the Intermediate data encryption
  feature is enabled." );
	script_tag( name: "impact", value: "Successful exploitation will allow local users to
  obtain sensitive information by reading the file." );
	script_tag( name: "affected", value: "All versions of Hadoop 2.6.x" );
	script_tag( name: "solution", value: "Upgrade to Apache Hadoop version 2.7.x or
  later or disable the feature when running MapReduce jobs." );
	script_tag( name: "solution_type", value: "VendorFix" );
	script_xref( name: "URL", value: "http://seclists.org/oss-sec/2016/q1/344" );
	script_tag( name: "qod_type", value: "remote_banner_unreliable" );
	script_copyright( "Copyright (C) 2017 Greenbone Networks GmbH" );
	script_category( ACT_GATHER_INFO );
	script_family( "Web application abuses" );
	script_dependencies( "gb_apache_hadoop_detect.sc" );
	script_mandatory_keys( "Apache/Hadoop/Installed" );
	script_require_ports( "Services/www", 50070 );
	exit( 0 );
}
require("version_func.inc.sc");
require("host_details.inc.sc");
if(!hadoopPort = get_app_port( cpe: CPE )){
	exit( 0 );
}
if(!hadoopVer = get_app_version( cpe: CPE, port: hadoopPort )){
	exit( 0 );
}
if(IsMatchRegexp( hadoopVer, "^(2\\.6)" )){
	report = report_fixed_ver( installed_version: hadoopVer, fixed_version: "2.7.X" );
	security_message( data: report, port: hadoopPort );
	exit( 0 );
}

